;; C-
(global-set-key (kbd "C-q") 'quoted-insert)
(global-set-key (kbd "C-w") 'kill-region)
(global-set-key (kbd "C-e") 'move-end-of-line)
(global-set-key (kbd "C-r") 'isearch-backward)
(global-set-key (kbd "C-t") 'other-window)
(global-set-key (kbd "C-y") 'yank)
(global-set-key (kbd "C-u") (kbd "C-@ C-a C-w"))
(global-set-key (kbd "C-i") 'indent-for-tab-command)
(global-set-key (kbd "C-o") 'open-line)
(global-set-key (kbd "C-p") 'previous-line)
(global-set-key (kbd "C-a") 'move-beginning-of-line)
(global-set-key (kbd "C-s") 'isearch-forward)
(global-set-key (kbd "C-d") 'delete-char)
(global-set-key (kbd "C-f") 'forward-char)
(global-set-key (kbd "C-g") 'keyboard-quit)
(global-set-key (kbd "C-h") 'delete-backward-char)
(global-set-key (kbd "C-j") 'electric-newline-and-maybe-indent)
(global-set-key (kbd "C-k") 'kill-line)
(global-set-key (kbd "C-l") 'recenter-top-bottom)
(global-set-key (kbd "C-z") 'view-mode)
;(global-set-key (kbd "C-x") ')
;(global-set-key (kbd "C-c") ')
(global-set-key (kbd "C-v") 'scroll-up-command)
(global-set-key (kbd "C-b") 'backward-char)
(global-set-key (kbd "C-n") 'next-line)
;(global-set-key (kbd "C-m") ')

;; M-
(global-set-key (kbd "M-q") nil)
(global-set-key (kbd "M-w") 'whitespace-mode)
(global-set-key (kbd "M-e") nil)
(global-set-key (kbd "M-r") nil)
(global-set-key (kbd "M-t") nil)
(global-set-key (kbd "M-y") nil)
(global-set-key (kbd "M-u") 'upcase-region)
(global-set-key (kbd "M-i") nil)
(global-set-key (kbd "M-o") nil)
(global-set-key (kbd "M-p") nil)
(global-set-key (kbd "M-a") nil)
(global-set-key (kbd "M-s") nil)
(global-set-key (kbd "M-d") 'downcase-region)
(global-set-key (kbd "M-f") 'forward-word)
(global-set-key (kbd "M-g") 'goto-line)
(global-set-key (kbd "M-h") nil)
(global-set-key (kbd "M-j") 'eval-print-last-sexp)
(global-set-key (kbd "M-k") 'describe-key)
(global-set-key (kbd "M-l") 'linum-mode)
(global-set-key (kbd "M-z") nil)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-c") nil)
(global-set-key (kbd "M-v") 'scroll-down-command)
(global-set-key (kbd "M-b") 'backward-word)
(global-set-key (kbd "M-n") nil)
(global-set-key (kbd "M-m") nil)

;; C-x C-
;(global-set-key (kbd "C-x C-q") ')
(global-set-key (kbd "C-x C-w") 'window-resizer-do)
;(global-set-key (kbd "C-x C-e") ')
;(global-set-key (kbd "C-x C-r") ')
;(global-set-key (kbd "C-x C-t") ')
;(global-set-key (kbd "C-x C-y") ')
;(global-set-key (kbd "C-x C-u") ')
;(global-set-key (kbd "C-x C-i") ')
;(global-set-key (kbd "C-x C-o") ')
;(global-set-key (kbd "C-x C-p") ')
;(global-set-key (kbd "C-x C-a") ')
;(global-set-key (kbd "C-x C-s") ')
;(global-set-key (kbd "C-x C-d") ')
;(global-set-key (kbd "C-x C-f") ')
;(global-set-key (kbd "C-x C-g") ')
;(global-set-key (kbd "C-x C-h") ')
;(global-set-key (kbd "C-x C-j") ')
;(global-set-key (kbd "C-x C-k") ')
;(global-set-key (kbd "C-x C-l") ')
;(global-set-key (kbd "C-x C-z") ')
;(global-set-key (kbd "C-x C-x") ')
;(global-set-key (kbd "C-x C-c") ')
;(global-set-key (kbd "C-x C-v") ')
(global-set-key (kbd "C-x C-b") 'buffer-menu)
;(global-set-key (kbd "C-x C-n") ')
;(global-set-key (kbd "C-x C-m") ')
