(setq-default indent-tabs-mode nil)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq inhibit-startup-message t)
(setq inhibit-startup-echo-area-message t)
(setq visible-bell t)
(setq require-final-newline t)
(setq scroll-step 1)
(show-paren-mode t)
(line-number-mode t)
(column-number-mode t)
(setq mode-line-position
      (let ((show-command-name '(:eval (format "[%s]" (prin1-to-string last-command)))))
        (reverse (cons show-command-name (reverse mode-line-position)))))
